    <?php
      require_once 'aanroepingen/connectie.php';
      include_once 'aanroepingen/header.php';
    ?>

    <h1> Over EenmaalAndermaal </h1>
    <p> 
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada felis, ac scelerisque risus. Suspendisse mollis lorem leo, nec tempus urna porttitor vitae. Pellentesque nunc est, mollis nec nisi vel, molestie bibendum mauris. Nullam eu porta nisl, sed euismod est. Cras tellus nisi, posuere sit amet ligula in, dictum scelerisque ligula. Ut nec risus iaculis, ullamcorper felis eget, ultrices odio. Integer vel purus id neque sodales imperdiet. Mauris congue turpis elit, ac pharetra lacus volutpat a. Sed non gravida nulla. Etiam sem diam, imperdiet sit amet sem eget, lobortis egestas nunc. Ut tellus mi, lacinia non sem pellentesque, suscipit pretium magna.
      Ut vitae turpis tincidunt mi blandit ullamcorper. Vivamus vitae dolor porttitor, tempus turpis non, pulvinar quam. Duis placerat sem sem, sit amet bibendum odio luctus eget. Integer quis orci lorem. Curabitur vitae auctor nisi. Nullam at dui tristique, consequat felis a, ullamcorper nisi. Vestibulum purus erat, luctus non dolor in, cursus dictum ex. Nulla urna arcu, efficitur eget odio at, ornare suscipit odio. In non pretium sapien. Duis efficitur, lorem quis maximus pulvinar, orci erat eleifend neque, non faucibus enim nisl et lectus. Proin sagittis nulla at risus mollis, et feugiat turpis facilisis.
      Phasellus et dolor in enim efficitur elementum interdum et ligula. Donec feugiat vehicula vulputate. Fusce dignissim placerat placerat. Cras porta magna at elit vestibulum, sodales sodales erat hendrerit. In tempor blandit sapien a iaculis. Etiam non dolor id purus sagittis malesuada. Phasellus sapien risus, laoreet sit amet libero a, molestie commodo leo. Vivamus mauris orci, sollicitudin ultrices neque vitae, posuere feugiat augue. Proin id auctor leo, vel congue diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vestibulum aliquam urna tellus, id faucibus nunc feugiat eu.
      Sed egestas, augue nec posuere condimentum, nunc ante fermentum nisi, commodo tincidunt leo ante eu massa. Quisque sit amet aliquet eros. Ut lacus sem, pellentesque gravida blandit a, commodo sed purus. Curabitur tempus neque felis, in aliquam tellus faucibus eu. Vivamus id ullamcorper risus, in faucibus sem. In vulputate massa eu dui sollicitudin, in malesuada justo efficitur. Mauris at eleifend erat. Pellentesque laoreet efficitur rutrum. Donec vehicula cursus posuere. Maecenas rhoncus aliquet diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus congue consequat consectetur. Sed feugiat libero et nibh finibus malesuada. Aliquam commodo magna diam, non sollicitudin sem consequat vel. Praesent efficitur arcu odio, quis convallis ipsum tincidunt maximus.
      Nullam non nisi quis nunc lobortis pretium a sit amet ligula. Quisque tristique vulputate tortor vel porttitor. Mauris in nunc non nisl finibus facilisis nec quis nunc. Praesent augue leo, eleifend at orci ac, tristique fermentum mi. In blandit eleifend rutrum. Nunc ac orci vel neque viverra commodo. Quisque nec feugiat nibh, sed pellentesque lacus.
    </p>

    <?php
      include_once 'aanroepingen/footer.html';
    ?>